export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN", NOT_FOUND: "NOT_FOUND",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  STORE_NOT_FOUND: "STORE_NOT_FOUND",

  STOCK_NOT_FOUND: "STOCK_NOT_FOUND",

  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

  INVALID_TRANSFER: "INVALID_TRANSFER",

}  as const;